### ISSUE TITLE
Support for custom wrapper

### ISSUE THREAD

**Issue by lauridskern** [gmsgowtham/react-native-marked#297]
Currently, it uses Flatlist which creates some issues with my use case. Does it make sense if we could have a custom wrapper so we could use a normal View instead of a Flatlist for example?

**Comment by gmsgowtham** [comment]
Yeah, makes sense. I'll have a look.

**Comment by anirudhsama** [comment]
Hi, even I have a similar issue. I'm want to embed this inside a scrollview which has some other items and currently it gives an error.

**Comment by anirudhsama** [comment]
Thanks! Will try it out!

**Comment by anirudhsama** [comment]
Can the API be similar to the previous <Markdown> component and it just returns the list of elements in a Fragment?

**Comment by gmsgowtham** [comment]
> Can the API be similar to the previous component and it just returns the list of elements in a Fragment?

No. The point of `useMarkdown` hook is to implement the "list of elements in a Fragment" by yourself.

**Comment by gmsgowtham** [comment]
v4.0.0 has support for custom wrapper using hook.
