### ISSUE TITLE
feat: Possibility to select the text

### ISSUE THREAD

**Issue by matheuswr89** [gmsgowtham/react-native-marked#300]
I wonder if it is possible to enable text selection in the cases of link, code block, plain text, heading, etc. Because if the user wants to copy something to paste later somewhere that would make it easier.

It would look something like (assuming it is a Text component):
```
<Text selectable>My text here</Text>
```

**Comment by gmsgowtham** [comment]
Supported as of [v4.0.2](https://github.com/gmsgowtham/react-native-marked/releases/tag/v4.0.2)
