### ISSUE TITLE
Do you plan to introduce a dropdown? 

### ISSUE THREAD

**Issue by pixelkoduje** [gmsgowtham/react-native-marked#306]
Hello, great Library. Do you plan to introduce a dropdown, similar to github, or just to be able to use a dropdown. Because I have to use markdown a few times in one place and write a custom dropdown. 
![Screenshot_2023-05-03-16-05-43-511_com android chrome](https://user-images.githubusercontent.com/102321542/235940701-f5e4b9ae-90dc-44ed-9f95-cb4fd70fb875.jpg)

**Comment by gmsgowtham** [comment]
I guess this is just HTML powered dropdown. So no plans to support it.

**Comment by KULTI1995** [comment]
![image](https://user-images.githubusercontent.com/14282128/235980268-0d757bf7-7f57-4bf8-b1e8-92c4f3713301.png)
I'm not talking about supporting html. And the ":::" tag, which will cause the content inside it to be treated as "Accordion". And I am asking because it will be necessary for me and I am wondering if you are able to implement it or do I need to do it myself.

**Comment by KULTI1995** [comment]
I can see that it can be implemented without the slightest problem. Are you able to create a function - like any other that passes??
`details(summaryText: string, children: ReactNode[], styles?: ViewStyle): ReactNode;`

![image](https://user-images.githubusercontent.com/14282128/235984944-038b8665-0760-445b-89f6-69b7081bc63a.png)

**Comment by gmsgowtham** [comment]
> ![image](https://user-images.githubusercontent.com/14282128/235980268-0d757bf7-7f57-4bf8-b1e8-92c4f3713301.png) I'm not talking about supporting html. And the ":::" tag, which will cause the content inside it to be treated as "Accordion". And I am asking because it will be necessary for me and I am wondering if you are able to implement it or do I need to do it myself.

If I'm not wrong, Github Flavored Markdown supports accordion using HTML, which cannot be handled by this library at the moment.

And I don't see `:::` as a spec for accordion. I can probably support this in the future with the use of custom plugin support. But nothing at the moment.

**Comment by gmsgowtham** [comment]
> Or maybe otherwise - take a look. These are reserved github tags and marked.js handles them without any problem. And you are using this library.
> 
> https://bit.ly/3LsJsO4
> 
> And it generates code that the library uses. Just a question, how to handle this tag that is generated and falls into your code?

Yeah, this library uses Marked.js under the hood. But Marked.js is HTML first, so we cannot take full advantage of it. This lib just relies on it for parsing the markdown and get the tokens out of it. The tokens are then custom rendered to RN components. 





> I can see that it can be implemented without the slightest problem. Are you able to create a function - like any other that passes?? `details(summaryText: string, children: ReactNode[], styles?: ViewStyle): ReactNode;`
> 
> ![image](https://user-images.githubusercontent.com/14282128/235984944-038b8665-0760-445b-89f6-69b7081bc63a.png)

`RendererInterface` just implements all the tokens that are supported by Marked.js.

**Comment by pixelkoduje** [comment]
That's why I'm talking about it - Can you, as you do on the occasion of each marker rendered by marked, give an endpoint for the functions for my example from the link. Because I wouldn't want to make a separate repository.

**Comment by gmsgowtham** [comment]
What kinda endpoint you're referring to?

**Comment by pixelkoduje** [comment]
https://bit.ly/3LsJsO4 - Look, marked.js supports details...

**Comment by gmsgowtham** [comment]
Okay, as explained above, this library doesn't support even though it uses marked.js. Its a limitation of this lib which cannot be addressed easily.

BTW, this lib uses lexer data which contains `html` tokens.

<img width="1285" alt="Screenshot 2023-05-03 at 11 15 55 PM" src="https://user-images.githubusercontent.com/24909879/236001384-9289f2fc-f233-4811-beea-d38f49ceccf5.png">

**Comment by KULTI1995** [comment]
I understand, and you are able to create a point. final function for this type of html stuff? And everyone, at least now, will be able to create various integrations on their own. It will take little time, and I'm afraid that we will wait for this integration and the library will be abandoned. And it will be useful anyway.
