### ISSUE TITLE
Library not working

### ISSUE THREAD

**Issue by KULTI1995** [gmsgowtham/react-native-marked#308]
https://snack.expo.dev/jf5Fih2fD

**Comment by gmsgowtham** [comment]
The issue is from Snack https://github.com/expo/snack/issues/383

**Comment by gmsgowtham** [comment]
[CodeSandbox](https://codesandbox.io/)  can be used as React Native Web is supported.

ie. https://codesandbox.io/s/react-native-marked-l2hpi3?file=/src/App.js
