### ISSUE TITLE
feat: SVG image support 

### ISSUE THREAD

**Issue by matheuswr89** [gmsgowtham/react-native-marked#320]
Taking into account the following markdown:

`[![jwt_log](https://jwt.io/img/badge-compatible.svg)](https://jwt.io)`

As you can see, instead of a normal text it passes an image markdown. And the lib doesn't support that. Would it be possible an implementation to work around this?

**Comment by gmsgowtham** [comment]
Can you please provide a repro?? Maybe with https://peerpad.net

**Comment by matheuswr89** [comment]
@gmsgowtham I put an example there: https://peerpad.net/#/r/markdown/DF64gyxxf5vcqC4WScgkeLgBNyUR6K2NXj67mW1epG7N/4XTTM4EkZihG7oJGHQUCTvM4m75DePx7b91wSiGKa2LwbJs9N

**Comment by gmsgowtham** [comment]
Can't access the link. It could be peerpad issue. Can you please share it via [https://marked.js.org/demo/](https://marked.js.org/demo/?text=Marked%20-%20Markdown%20Parser%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0A%5BMarked%5D%20lets%20you%20convert%20%5BMarkdown%5D%20into%20HTML.%20%20Markdown%20is%20a%20simple%20text%20format%20whose%20goal%20is%20to%20be%20very%20easy%20to%20read%20and%20write%2C%20even%20when%20not%20converted%20to%20HTML.%20%20This%20demo%20page%20will%20let%20you%20type%20anything%20you%20like%20and%20see%20how%20it%20gets%20converted.%20%20Live.%20%20No%20more%20waiting%20around.%0A%0AHow%20To%20Use%20The%20Demo%0A-------------------%0A%0A1.%20Type%20in%20stuff%20on%20the%20left.%0A2.%20See%20the%20live%20updates%20on%20the%20right.%0A%0AThat%27s%20it.%20%20Pretty%20simple.%20%20There%27s%20also%20a%20drop-down%20option%20above%20to%20switch%20between%20various%20views%3A%0A%0A-%20**Preview%3A**%20%20A%20live%20display%20of%20the%20generated%20HTML%20as%20it%20would%20render%20in%20a%20browser.%0A-%20**HTML%20Source%3A**%20%20The%20generated%20HTML%20before%20your%20browser%20makes%20it%20pretty.%0A-%20**Lexer%20Data%3A**%20%20What%20%5Bmarked%5D%20uses%20internally%2C%20in%20case%20you%20like%20gory%20stuff%20like%20this.%0A-%20**Quick%20Reference%3A**%20%20A%20brief%20run-down%20of%20how%20to%20format%20things%20using%20markdown.%0A%0AWhy%20Markdown%3F%0A-------------%0A%0AIt%27s%20easy.%20%20It%27s%20not%20overly%20bloated%2C%20unlike%20HTML.%20%20Also%2C%20as%20the%20creator%20of%20%5Bmarkdown%5D%20says%2C%0A%0A%3E%20The%20overriding%20design%20goal%20for%20Markdown%27s%0A%3E%20formatting%20syntax%20is%20to%20make%20it%20as%20readable%0A%3E%20as%20possible.%20The%20idea%20is%20that%20a%0A%3E%20Markdown-formatted%20document%20should%20be%0A%3E%20publishable%20as-is%2C%20as%20plain%20text%2C%20without%0A%3E%20looking%20like%20it%27s%20been%20marked%20up%20with%20tags%0A%3E%20or%20formatting%20instructions.%0A%0AReady%20to%20start%20writing%3F%20%20Either%20start%20changing%20stuff%20on%20the%20left%20or%0A%5Bclear%20everything%5D(%2Fdemo%2F%3Ftext%3D)%20with%20a%20simple%20click.%0A%0A%5BMarked%5D%3A%20https%3A%2F%2Fgithub.com%2Fmarkedjs%2Fmarked%2F%0A%5BMarkdown%5D%3A%20http%3A%2F%2Fdaringfireball.net%2Fprojects%2Fmarkdown%2F%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by matheuswr89** [comment]
I think now it has: [access here](https://marked.js.org/demo/?text=Link%20with%20image%20instead%20of%20text%3A%20%0A%0A%5B!%5Bjwt_log%5D(https%3A%2F%2Fjwt.io%2Fimg%2Fbadge-compatible.svg)%5D(https%3A%2F%2Fjwt.io)%0A%0A---%0A%0ALink%20with%20text%3A%0A%0A%5BJWT%5D(https%3A%2F%2Fjwt.io)&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by gmsgowtham** [comment]
Okay, thanks. Looks like its already implemented. 

https://codesandbox.io/s/react-native-marked-320-sovt4w?file=/src/App.js

**Comment by matheuswr89** [comment]
Apparently, when it's compiled for a normal app and when the image is an svg, it doesn't render. I had to use lib react-native-svg to be able to render the svg in a custom render:
```
import { SvgUri } from "react-native-svg";
....
linkImage(
    href: string,
    imageUrl: string,
    alt?: string,
    style?: ImageStyle
  ): ReactNode {
    const imageNode = this.image(imageUrl, alt, style);
    console.log(imageNode);
    return (
      <TouchableHighlight
        accessibilityRole="link"
        accessibilityHint="Opens in a new window"
        onPress={() => Linking.openURL(href)}
        key={this.getKey()}
      >
        {imageUrl.includes(".svg") ? (
          <SvgUri width="100" height="100" uri={imageUrl} />
        ) : (
          imageNode
        )}
      </TouchableHighlight>
    );
  }
```

**Comment by gmsgowtham** [comment]
Got it. SVGs are not supported. I'll have a look

**Comment by gmsgowtham** [comment]
SVG support has been added in [v4.1.0](https://github.com/gmsgowtham/react-native-marked/releases/tag/v4.1.0)
