### ISSUE TITLE
Why was node bumped to version 18?

### ISSUE THREAD

**Issue by efstathiosntonas** [gmsgowtham/react-native-marked#367]
Hi, thank you for this module. May I ask why node has been bumped to version 18? This is a breaking change for many devs.

**Comment by gmsgowtham** [comment]
Sorry if the latest release broke your development flow. 

The reason is to support the latest release of marked https://github.com/markedjs/marked/compare/v4.3.0...v5.0.0

**Comment by efstathiosntonas** [comment]
Thanks for the clarification, can you bump this: 

https://github.com/gmsgowtham/react-native-marked/blob/5972610d5e0ffdef41f5deafcd833f69870bdf97/package.json#L169 

to be `18.16.0`?

Thanks

**Comment by efstathiosntonas** [comment]
thanks @gmsgowtham, keep it up!

**Comment by gmsgowtham** [comment]
It was my bad. v18.16.0 has an issue with Jest, so blindly restricted it to v18.15.0 😅 

[v5.0.2](https://github.com/gmsgowtham/react-native-marked/releases/tag/v5.0.2) Addressed it
