### ISSUE TITLE
The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by smooth1884** [gmsgowtham/react-native-marked#384]
When building with expo, in my case iOS internal distribution build I get the following build error:

`error react-native-marked@5.0.4: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.18.1"`

I will check which version doesn't requires >=18 and supports 16.18.1 (which is what expo is using), and use that one for now. 
EDIT: 4.1.1 works, as there is no node version specified in package.json

or do you have any other suggestions on how I can fix this issue using the latest version?

**Comment by gmsgowtham** [comment]
@smooth1884 The v5 version corresponds to the most recent release of marked.js, which requires Node v18. Therefore, if you haven't upgraded expo yet, you can continue using v4 for now.
