### ISSUE TITLE
Why is node 18 required?

### ISSUE THREAD

**Issue by abejfehr** [gmsgowtham/react-native-marked#385]
The restriction in the `engine` field is pretty unfortunate, I'm having troubles with an Expo build because their default version is 16.x.x, even though I updated my .nvmrc file to say `19`.

Is there an actual reason that a node version less than 18 wouldn't work?

**Comment by abejfehr** [comment]
In case anyone needs this, apparently the way to specify node version on Expo EAS is [in the eas.json](https://docs.expo.dev/build/eas-json/), the .nvmrc is not used.

Still, the requirement for node >= 18 could probably be more lax

**Comment by gmsgowtham** [comment]
Please ref: https://github.com/gmsgowtham/react-native-marked/issues/367#issuecomment-1573357137

Closing this as duplicate.
