### ISSUE TITLE
 requireNativeComponent: "RNSVGSvgViewAndroid" was not found in the UIManager on linkImage

### ISSUE THREAD

**Issue by nick-delirium** [gmsgowtham/react-native-marked#402]
First of all, great library. Its been a great help while I'm building a custom lemmy client :)

I'm using latest v of this library + 13.4.0 of react-native-svg and trying to render md I'm getting from a request.

MD content:
```
* Admin @ [lemm.ee](https://lemm.ee), a general-purpose Lemmy instance\n* Professional software engineer\n* Lemmy contributor\n\n[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/S6S7M9RT8)
```

here's content that gets passed to linkImage renderer:
```
 href: https://ko-fi.com/S6S7M9RT8 
 imageUrl: https://ko-fi.com/img/githubbutton_sm.svg
 alt: ko-fi
 style:{"resizeMode": "cover"}
```

as a result, I'm getting `Invariant Violation: requireNativeComponent: "RNSVGSvgViewAndroid" was not found in the UIManager.
`

I confirmed that by creating a custom renderer for this component specifically.

Full stacktrace attached, highlighted root on bottom:
<img width="635" alt="image" src="https://github.com/gmsgowtham/react-native-marked/assets/23126999/cd041384-6273-4c39-83f3-d6c377c232f0">

**Comment by nick-delirium** [comment]
did some more debugging and its probably caused by `SvgFromXml`? Not sure tbh, if I try to render SvgFromUri it fails with different error (`tried to register two views with the same name RNSVGSvgView,`) so I'm gonna replace svg hrefs with just button with alt probably for now

**Comment by gmsgowtham** [comment]
@nick-delirium It looks like`react-native-svg` upstream issue. Can you please check https://github.com/software-mansion/react-native-svg/issues/1944

Also a small repro would be helpful 😄
