### ISSUE TITLE
Suport to HTML

### ISSUE THREAD

**Issue by matheuswr89** [gmsgowtham/react-native-marked#432]
Its possible to add suport to HTML tags with the library [react-native-render-html](https://www.npmjs.com/package/react-native-render-html)? This library transforms HTML tags into native react native components. And it's possible to customize any tags.

**Comment by gmsgowtham** [comment]
@matheuswr89 `react-native-render-html` can be integrated using custom renderer. 

```jsx
class CustomRenderer extends Renderer implements RendererInterface {
  constructor() {
    super();
  }

  html(text: string, styles?: TextStyle): ReactNode {
    return (
      <RenderHtml source={text} />
    );
  }

}
```
