### ISSUE TITLE
Read .md files

### ISSUE THREAD

**Issue by Jay-Salisbury** [gmsgowtham/react-native-marked#513]
I'm looking to share .md files between a web project running on Eleventy and a RN application. I believe that I should be able to import md files with react-native-fs and then process the imported content with react-native-marked. However, I wanted to ask is there's not a more elegant way to do this from within react-native-marked itself. I'm guessing that others using this plugin might be doing something similar. Thanks for the help!

**Comment by gmsgowtham** [comment]
Hi @Jay-Salisbury, Its out of scope for this library. 

> I believe that I should be able to import md files with react-native-fs and then process the imported content with react-native-marked.

This should be possible. You can create a wrapper around `react-native-fs` and `react-native-marked` to process the files. And I can't think of any other solution.
