### ISSUE TITLE
backgroundColor of User-provided theme is not applied

### ISSUE THREAD

**Issue by NicoHubrach** [gmsgowtham/react-native-marked#537]
As stated in the title, it seems like the provided 'backgroundColor' of a UserTheme is not applied to a Markdown Hierarchy.
e.g.
```
        <View style={{
            flex: 1,
            backgroundColor: 'black',
        }}>
            <Markdown value={"# HALLO"} theme={{
                colors: {
                    background: 'black',
                    border: 'black',
                    code: 'black',
                    link: 'black',
                    text: 'black',
                }
            }} />
        </View>
```
I would expect the View to be completly black, but instead it is white with the Text being black.
I suspect that the Markdown Element lays on top of the whole View and the background Color is not  correctly applied.
If this is intended behaviour I'd like to ask how you would go about changing the background color of, lets say, a h1 component.

**Comment by gmsgowtham** [comment]
@NicoHubrach Can you please post a reproduction?

**Comment by NicoHubrach** [comment]
Thanks for your quick response!
[This](https://github.com/NicoHubrach/backgroundColorNotAppliedRepro) is a working bare minimum.
It uses expo go and just your library. Hope this helps!

**Comment by gmsgowtham** [comment]
Looks like a regression, I'll fix it ASAP

**Comment by gmsgowtham** [comment]
@NicoHubrach Found the issue.
1. Background color wasn't overridden when specified. The property will be deprecated in favor of flatlist style prop which IMO is straightforward.
2. H1 style wasn't inheriting the text color.

This PR will address those issues https://github.com/gmsgowtham/react-native-marked/pull/539

**Comment by NicoHubrach** [comment]
Thank you for the quick fix! Much appreciated (:
