### ISSUE TITLE
Italics not styleable

### ISSUE THREAD

**Issue by NicoHubrach** [gmsgowtham/react-native-marked#543]
**Describe the bug**
The underlying text component for italics is not styleable via the 'styles' prop of `<Markdown />`

**Reproducible Code**
```
function App() {
  return (
    <Markdown
      value={markdownString}
      styles={{
        strong: {
          color: 'red',
        },
        /* This functionality is missing */
        italic : {
          color: 'green',
        },
      }}
    />
  );
}

const markdownString = `
**bold**
_italic_
`;
```

**Expected behavior**
I would expect. that the italics component to be styleable just like every other component. e.g. `strong`, `h1`

**Environment**
- **react-native-marked Version:**
  `4.1.1`

**Comment by NicoHubrach** [comment]
I just realized you are using 'marked' for your base and that does not provide funtionality for detecting italics either.
Do you have any idea how this could be achieved?

**Comment by gmsgowtham** [comment]
@NicoHubrach The key you're looking for is `em`.

```jsx
function App() {
  return (
    <Markdown
      value={markdownString}
      styles={{
        strong: {
          color: 'red',
        },
        em : {
          color: 'green',
        },
      }}
    />
  );
}

const markdownString = `
**bold**
_italic_
`;
```
