### ISSUE TITLE
BackgroundColor not styleable

### ISSUE THREAD

**Issue by NicoHubrach** [gmsgowtham/react-native-marked#559]
**Describe the bug**
Space inbetween Elements is not styleable

**Reproducible Code**
[Here](https://github.com/NicoHubrach/backgroundColorNotAppliedRepro/tree/master) is a repository showcasing the missing spots that are not styleable

**Expected behavior**
You can color 'a whole Screen to your liking, including the Space inbetween elements'

**Screenshots**
![image](https://github.com/gmsgowtham/react-native-marked/assets/69457613/9af299bd-e796-4492-a176-329b953799df)

**Environment**

- **React Native Version:**
  0.72.5

- **react-native-marked Version:**
  6.0.2

- **Platform:**
  Web (idk if on any other platform. I suspect)

**Additional context**
This Bug was found in the same context as described in #537

**Comment by flogy** [comment]
Not sure if I don't understand exactly, but couldn't you just use the flat list styling to colorize the gaps?

```tsx
<Markdown
  value={markdown}
  flatListProps={{
    style: {
      backgroundColor: 'red',
    },
  }}
/>
```

**Comment by gmsgowtham** [comment]
As suggested by @flogy, flatlist style prop or contentContainerStyle prop needs to used for background styling.
