### ISSUE TITLE
The content is not fully displayed

### ISSUE THREAD

**Issue by hongying-yang** [gmsgowtham/react-native-marked#697]
The following text is not fully displayed：

In the bustling streets of the RPG world, you've lost sight of Mamako. The crowd is thick, and the sound of merchants hawking their wares fills the air. Suddenly, you hear her call out to you, her voice laced with worry and relief.
                
                
                "Dear!" Mamako exclaims, her voice a blend of panic and relief as she finally spots you by the weaponry shop. "Oh, my heart nearly stopped! Why did you run off like that? It's dangerous to be alone here!"
                
                
                She approaches, her expression a mix of exasperation and adoration as she reaches out to gently adjust your clothing. Her touch is warm, her presence a comforting embrace amidst the chaos of the RPG world.

**Comment by gmsgowtham** [comment]
@hongying-yang Please share the markdown for reproducing the bug

**Comment by hongying-yang** [comment]
@gmsgowtham  
<img width="360" alt="截屏2024-08-23 11 56 07" src="https://github.com/user-attachments/assets/98e77df7-75bb-4e5f-88e1-a9a67ff3a22f">
![截屏2024-08-23 11 56 22](https://github.com/user-attachments/assets/67a0d629-d5ad-4fb2-8f55-f4c3b80c35f4)

Markdown value is:


In the bustling streets of the RPG world, you've lost sight of Mamako. The crowd is thick, and the sound of merchants hawking their wares fills the air. Suddenly, you hear her call out to you, her voice laced with worry and relief.
                
                
                "Dear!" Mamako exclaims, her voice a blend of panic and relief as she finally spots you by the weaponry shop. "Oh, my heart nearly stopped! Why did you run off like that? It's dangerous to be alone here!"
                
                
                She approaches, her expression a mix of exasperation and adoration as she reaches out to gently adjust your clothing. Her touch is warm, her presence a comforting embrace amidst the chaos of the RPG world.

**Comment by gmsgowtham** [comment]
This is the expected behavior. The text is not wrapped by default i.e Github.

<img width="307" alt="Screenshot 2024-09-01 at 8 24 40 PM" src="https://github.com/user-attachments/assets/ffa43807-2376-4cc2-8da9-2d70adf5fd93">
