### ISSUE TITLE
The last line of copy cannot be scrolled

### ISSUE THREAD

**Issue by hongying-yang** [gmsgowtham/react-native-marked#712]
When I put Markdown on the Pressable, the last line won't scroll across

![截屏2024-09-10 17 28 22](https://github.com/user-attachments/assets/e20e7595-8c97-4e84-87ae-13c72631e558)
  

const data = {
    content:
      "In the bustling streets of the RPG world, you've lost sight of Mamako. The crowd is thick, and the sound of merchants hawking their wares fills the air. Suddenly, you hear her call out to you, her voice laced with worry and relief.\n" +
      '            "Dear!" Mamako exclaims, her voice a blend of panic and relief as she finally spots you by the weaponry shop. "Oh, my heart nearly stopped! Why did you run off like that? It\'s dangerous to be alone here!"\n' +
      '            \n' +
      '            \n' +
      '            She approaches, her expression a mix of exasperation and adoration as she reaches out to gently adjust your clothing. Her touch is warm, her presence a comforting embrace amidst the chaos of the RPG world.',
  }

**Comment by gmsgowtham** [comment]
Couldn't reproduce the bug.
