### ISSUE TITLE
The content not suport underline text with tag <u>

### ISSUE THREAD

**Issue by phanthaoIT** [gmsgowtham/react-native-marked#767]
The content not render underline text. Ex <u>Underline</u>

**Comment by gmsgowtham** [comment]
@phanthaoIT Please provide a smaller reproduction

**Comment by phanthaoIT** [comment]
Hi @gmsgowtham, I have the small demo in the [codesanbox](https://codesandbox.io/p/devbox/p9rdpl). Thank you in advance

**Comment by gmsgowtham** [comment]
@phanthaoIT Rendering HTML tags isn't supported, please refer https://github.com/gmsgowtham/react-native-marked/issues/290
