### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGRect

### ISSUE THREAD

**Issue by jacobhummel** [gmsgowtham/react-native-marked#782]
**Describe the bug**
Error when using this library with react-native-svg 15.

**To Reproduce**
1.`yarn add react-native-marked react-native-svg` or `npx expo install react-native-marked react-native-svg`
2. Build dev client (if using expo) and run the app on iOS

**Reproducible Code**
-

**Screenshots**

<img src="https://github.com/user-attachments/assets/8d2f7fd5-f9cb-48bd-ae12-5226a1df1d6c" width="350" />

**Environment**

- **React Native Version:**
`"react-native": "0.74.5",`
`"expo": "~51.0.38",`

- **react-native-marked Version:**
`"react-native-marked": "^6.0.5",`

- **react-native-svg Version:**
`"react-native-svg": "15.2.0",`

- **Platform:**
iOS

**Additional context**
Works fine when running on react-native-web, no errors.

**Comment by gmsgowtham** [comment]
@jacobhummel Can you please try with react-native-svg@13?? v15 isn't supported yet

**Comment by jacobhummel** [comment]
@gmsgowtham v15 did seem to work when I was trying to update the sample project. See here: https://github.com/gmsgowtham/react-native-marked/pull/783. Unfortunately I have other dependencies that require `react-native-svg` v15 so I don't think downgrading is an option for me.

**Comment by jacobhummel** [comment]
I believe my error is caused by the fact that we use https://github.com/kristerkari/react-native-svg-transformer ^1.5.0. I just commented out our usage of that and all of our SVGs and react-native-marked works well even with `react-native-svg` 15 installed. https://github.com/kristerkari/react-native-svg-transformer/issues/86

**Comment by jacobhummel** [comment]
I think I was wrong. I think this is actually what fixed it for me. Though I think the error is still caused by using `react-native-svg-transformer`

```
"overrides": {
    "react-native-marked": {
      "react-native-svg": "15.2.0"
    }
  }
```

**Comment by schimini** [comment]
His @jacobhummel , how were you able to make this work?

```js
const { getDefaultConfig } = require("@expo/metro-config");

// eslint-disable-next-line no-undef
const defaultConfig = getDefaultConfig(__dirname);
defaultConfig.resolver.sourceExts.push("cjs");

defaultConfig.transformer = {
  ...defaultConfig.transformer,
  babelTransformerPath: require.resolve("react-native-svg-transformer/expo"),
};

defaultConfig.resolver.assetExts = defaultConfig.resolver.assetExts.filter(
  (ext) => ext !== "svg",
);
defaultConfig.resolver.sourceExts.push("svg");
module.exports = defaultConfig;
```

I have this

"react-native-svg-transformer": "^1.5.0",
"react-native-svg": "15.8.0",
    "react-native-marked": "^6.0.5",
    
 and it still gives me the same error when using 
 
 ```import { Renderer, RendererInterface, useMarkdown } from "react-native-marked"; ```

**Comment by Arsenii-Zhelobetskyi** [comment]
@gmsgowtham can I  ask you, are you  planning to add support for new  react-native-svg any soon ? Found your library very promising for my project...

**Comment by gmsgowtham** [comment]
I'll add support for it

**Comment by gmsgowtham** [comment]
RNSVG is upgraded. Ref: [v6.0.6](https://github.com/gmsgowtham/react-native-marked/releases/tag/v6.0.6)

**Comment by Darren-Ter** [comment]
I encountered this error again in the latest version `v6.0.6` and resolved it by updating the pre-installed `react-native-svg` in my Expo project to `15.10.1`, which matches the version used by [`v6.0.6`](https://github.com/gmsgowtham/react-native-marked/commit/09909e990d0eeeeb43f70d5700c43b7aa2187f9c)

(I am using `bun` as package manager, and since it doesn't support nested overrides, so the solution mentioned in https://github.com/gmsgowtham/react-native-marked/issues/782#issuecomment-2523870575 doesn't work for me)

**Comment by jacobhummel** [comment]
@gmsgowtham @Darren-Ter I believe I have a fix for Darren and my issue (even though I resolved mine using an `overrides` workaround) https://github.com/gmsgowtham/react-native-marked/pull/790
